### ISSUE TITLE
공공데이터 API 폐기 이슈

### ISSUE THREAD

**Issue by realdevelope** [kebin0613/SSAC_Team#14]
공공데이터활용지원센터 로 부터 저희가 현재 적용해 놓은 
'요소수 중점 유통 주유소 재고현황' API 폐기안내 메일을 받았습니다...
그래서 29일날 새로운 API를 적용해야 합니다. 
->아마 API 형식이 달라질 것으로 예상되나 빠르게 재 연동 하도록 하겠습니다.

## 폐기 사유
  - 현재 개발전 파일데이터에서 변환된 임시API가 하루에 2번 업데이트가 되어있었는데, 
     현재 본 API를 새로 개방하면서 현재 API를 폐기처리 한다는 내용입니다.

## 폐기 예정일
- 11월 29일 월요일

## 새로운 API 
- 이름 : '환경부_요소수 중점 유통 서비스 재고현황 조회서비스'
- 변경 내용 : 하루 2번 업데이트 -> 5분단위로 업데이트 ( 유통 주유소에서 2시간 간격으로 재고현황을 입력받는 형식)
- 오픈 일정 : 29일 예정

## 대처 방안
- 현재 새로운 API 활용신청 완료
->정식오픈일 29일(월) 되자마자 재연동 할 예정
![asdfvewrgfef](https://user-images.githubusercontent.com/48710889/143678536-20437ace-4a0e-4f32-a706-16ef222168a7.jpg)

## 우려되는 점
- 29일에 오픈되지 않을 시 배포기간 딜레이 될 것으로 보입니다.

**Comment by seungwanRyu01** [comment]
저도 공공데이터포털을 가입해놓은 터라 해당 부분 메일로 알게되었습니다! 그러면 해당 api가 변경된다면 저희가 해놓은 설정들도 변경이 필요한가요??

**Comment by realdevelope** [comment]
아니요! 여러분들이 따로 변경하실 건 없습니다.
월요일에 테스트시 데이터 없는 순수 지도만 뜨는 상황이 될 수 있다는 점 정도?!

**Comment by sue6e2** [comment]
아하 그렇군요! 하루에 2번 업데이트 되던 것이 5분마다 업데이트 된다니 좋네요!!
29일에 오픈되었으면 좋겠네요 :)

**Comment by realdevelope** [comment]
우선 변경된 API 적용 및 코드 수정 완료 했습니다. 
여러가지 변화 중 큰 변화는 가격이 제공 된다는 점입니다�
![ffffff](https://user-images.githubusercontent.com/48710889/143779084-db2c0fd1-cb93-4cda-9cb6-bf1b739542d2.PNG)
�
