### ISSUE TITLE
Iac 배포 관련 공지

### ISSUE THREAD

**Issue by realdevelope** [kebin0613/SSAC_Team#15]
저희가 팀프로젝트로 요소수맵을 제작하여 배포한다고
제 지인 한테 이야기 했더니, Iac를  사용해보라고 권유 받고,
설명을 들은 후 도입 해보았습니다.

## IaC (Infrastructure as Code)
- 인프라에 사용되던 모든 설정들을 코드로 관리하기 위한 것으로 기존에서 쉽게 하지 못하던 것들이 
   클라우드가 자리잡게 되면서 가능

## terraform
- 인프라 전체를 안전하게 배포, 변경, 버전관리 등을 해주는 대표적인 도구
- 테라폼은 클라우드에 종속적이지 않아 AWS에서 GCP로 배포하거나, 
   그 반대로 하는 등 리소스에 대한 정의만 잘 되어 있다면 어떤 환경에서든 사용 가능하다

## terraform init
- 테라폼을 초기화 해주고 상태 파일 생성 등 현재 상태관리를 폴더 단위로 해줌
- 테라폼의 전체 환경 폴더 구조가 있고 하위에 글로벌 폴더 또는 모듈이나 각 개발환경에 맞춰 
   폴더를 위치 시키고 각 폴더별로 초기화를 해줌으로써 각 환경별로 테라폼이 상태를 관리한다.

## terraform plan
- 테라폼이 클라우드 환경에 배포하기 전 미리 한번 작동시켜서 정상 배포가 가능한지 체크하는 명령어

## terraform apply
- 실제 배포를 수행한다

---
### 다시 정리하자면
- 예를들어 설명해보자면 우리가 aws에 ec2 인스턴스를 한개 만들어야 한다고 할때,
   그러면 aws에 로그인하고 ec2 인스턴스에 들어가서 인스턴스 생성 → next 클릭 클릭 하며 생성해야 하는 것들을
   HCL(Hashicorp Configuration Language)로 관리할 수 있게 하는 도구이다.

### Ansible
- Ansible 은 파이썬으로 만들어진 환경 구성 자동화 툴
- 서버에서는 동일한 구성을 해야하는 클러스터들이 있는데, 예를들면 WAS를 띄워야 하는데 
  이걸 docker image로 당겨와서 container로 띄워줘야 하는 상황이고, 이것들을 여러개 띄워야 한다고 
  가정했을 때 개발자는 생성된 ec2 instance들에 들어가서 shell script를 실행시키거나 직접 수작업을 n번 해야 합니다.
  하지만 Ansible은 이러한 작업을 자동화 해주고, 환경 구성을 규격화 된 코드로 관리할 수 있게 해줍니다.

### 장점
- 같은 구성으로 서버를 띄우고 내릴수 있고, 그럴떄 안정적이다
- 더 확장될시 -> 새로운 구성만 붙여주면 그대로 서버를 올릴 수있음 (기존형태 유지)

### 우분투(ssh)에서 실행 하는 이유
- Ansible이 윈도우에서 잘안되서 우분투(ssh)에 구성
  -> cmd

### IaC 서버를 두는 이유
- 다른 사람도 공유가 가능 해야하기 때문에 IaC 서버를 따로 둠

### 결론
-  우선 생산성을 향상 시키기 위해 도입은 하되, 저희 모두 실제 필드에서 적용해보려면 좀더 공부가 필요 합니다.
-  현재 aws에 연동시켜 배포 성공 -> 지도부분과 태규님 작업한 부분 페이지가 무너지는 현상 발생 -> 보완필요
-  실행하는 법과 자세한 설명 회의 때 시연해서 보여 드리겠습니다.(백문이 불여일견)
- 저희 팀원 외에 PR로 인한 참여는 프로젝트 제작 부분에 참여한게 아닌 인프라적인 부분이기 때문에 어느정도 포용이 가능하다고 생각되나 여러분들의 생각이 궁금합니다.

**Comment by Bigjade97** [comment]
배포하는게 처음이라 잘 모르겠지만 같은 구성으로 서버를 띄우고 내릴수 있는게 좋은거 같습니다! 또 안정적이라니 좋고요.
회의때 봐야겠습니다! 
또 페이지 무너지는 현상 보완 빨리 해보겠습니다.

**Comment by sue6e2** [comment]
정리 감사합니다 :)
lac 사용해보는 것도 좋을 것 같아요! 내일 회의 때 보고 결정합시다!
저도 팀원 외에 PR로 인한 참여 포용 가능하다고 생각합니다.

**Comment by seungwanRyu01** [comment]
IAC에 대해 완전히 처음 들어보는 개념이라 생소하지만 특징에 대해 잘 기술해주신 덕에 어느 정도 이해가 되었습니다!
저도 팀원 외에 PR로 인한 참여는 지수님과 같은 생각입니다!

**Comment by realdevelope** [comment]
네넵!! 여러분들 의견 감사합니다 =)
저도 100% 이해 하에 적용한 게 아니다 보니 조금 미흡할 수 있는 점 양해 부탁 드리며,
내일 회의 때 보시고 최종 결정하는 걸로 하겠습니다.
