### ISSUE TITLE
뉴스API 배포시 안불러와지는 이슈

### ISSUE THREAD

**Issue by realdevelope** [kebin0613/SSAC_Team#35]
## 해당 문제의 원인
1) Nginx
2) outbound(나가는 패킷)이 씹힘
->위의 두가지로 추정 되었으나, 결론은 2번!

## 대표님이 말씀 하셨던 해결책은 x BUT 엄청난 인사이트가 되었음
yososumap.ga/v1/search/news.json 은 
Nginx에 요청 하는거라 애초에 말이 안됨
-> 프록시가 로컬로 들어오니까 로컬의 코드가 떴던 것!
-> 빌드가 되면서 바뀌면서 생기는 문제임!!!

## 해결하기 위해 적용한것
1. build.sh 
-> 프록시가 이미 올라가있으면 삭제해주는 코드 추가 작성(컨테이너)

2. package.json
-> "proxy": "http://yososumap.ga:3001" 작성

3. NewsList.js
-> 비동기 코드 전면 수정 
   axios.get('http://yososumap.ga:3001')
            .then(response => {
                setArticles(response.data);
            })
            .catch(err => console.error(err));
    }, []);

-> 현재 로컬에서는 에러가 나고 **배포서버에서만 됨**
-> 로컬에서 가능하게 하려면 package.json, NewsList.js 에서 주소 변경해줘야함

4. node로 중계서버(proxy)를 둠(3001)
-> 백단을 두어 간단하게 작성
-> CORS 다 허용
-> 키값도 프론트에서 하면 사람들이 볼 수있기에 여기로 이동

## 저희가 확인 해야할 것 
- 이슈가 생길 때마다  NGINX 내부 확인할 것
- 전반적으로 백 로직 및 관리 프로세스 학습하기 
- 현재 IaC에 설정된 aws가 프리티어로 수정

**Comment by seungwanRyu01** [comment]
몇일 째 고민해도 해결하기 어려운 이슈였는데 서버에 관한 배경지식이 부족하면 해결할 수 없는 문제였습니다 저도 이번 기회를 통해서 해당 파트에 대한 공부가 필요하다는 점을 절실히 느끼게 되었습니다 감사합니다!

**Comment by realdevelope** [comment]
맞습니다.. 저 또한 왜 사용해야하는지, 그리고 사용방법만 숙지하고있었을분 내부적으로 이해가 많이 부족한 상태여서
노션에 따로 실습하면서 문서화 하였으니 저희 팀원 모두 이번기회에 DevOps - Iac 에 대해 제대로 숙지하고 갑시다😊

**Comment by sue6e2** [comment]
감사합니다!!! 네네 이번 기회에 배워가면 좋을 것 같습니다!!!

**Comment by Bigjade97** [comment]
이게 왜 사용되는지 몰랐는데 실습하면서 제대로 숙지해야겠어요! 감사합니다.
