### ISSUE TITLE
현시각 기준 api서버 문제 발생 이슈

### ISSUE THREAD

**Issue by realdevelope** [kebin0613/SSAC_Team#37]
## 문제
- api 서버에 문제로 인해 현재 서비스중인 저희 '요소수 맵'에서
지도에 데이터를 가져오지 못해서 클러스터 자체가 뜨지 않고 있습니다.
(정확히 말하면 30초~1분 이 지나야 뜹니다)
![rfrfrfrfrfrfrfr](https://user-images.githubusercontent.com/48710889/144722114-0c074648-1877-4cdf-b729-c24144ccb131.PNG)

## 문제분석
- '요소수 맵' 의 인스턴스 성능 자체가 문제라면 사이트 접속부터 딜레이 걸려야 하는데 
그런게 아니라 지도위의 뜨는 클러스터만 느리게 (약 30초~1분 간헐적) 뜨는 것으로 보아
api 서버 문제인듯합니다.

## 문제 원인 파악완료
- 확실히 알고싶어서 공공데이터포털에 axios로 요청 보내봤더니 응답이 없네요....
<img width="691" alt="KakaoTalk_20211205_022827316" src="https://user-images.githubusercontent.com/48710889/144722310-cb511255-6237-44dd-b7c7-c35dc782a983.png">

## 대처
- 현재 공공데이터 포털에 오류신고 접수 완료했습니다.
![dfdfdfdfdfdfdfdfdf](https://user-images.githubusercontent.com/48710889/144722558-2a179669-c640-4368-8ab5-1a5daee7b946.PNG)

## 만약 공공데이터측의 대응이 느릴시 
 - 디비에 집어놓고 꺼내오는 방식으로 진행
 --> 공수가 많이 들어가게 되겠지만 1분마다 받아와서 db 업데이트 시켜놓고
       우리와 같이 실시간 서비스하는 상황에도 최신데이터 뿌려주면 되니 가능 할 것 같습니다.
--> 또한 지수님, 태규님께서 백앤드 구축 하고싶어하셨는데 잘됬고, 발표시간안에도 가능한 바운더리라고 생각됩니다. 물론 빠르게 구축해야 의미가 있긴 합니다.

## 더 효율적인 대처방안이 있으시면 자유롭게 말씀해주세요!!

**Comment by seungwanRyu01** [comment]
해당 데이터들을 디비에 넣어주면 정말 좋을 것 같기는 한데...해당 방법에 대해 고민을 좀 더 해보겠습니다

**Comment by sue6e2** [comment]
공공데이터측의 대응이 느리다면 디비에 데이터를 넣고 꺼내오는식으로 하면 좋을것 같아요! 빠르게 구축해서 발표날짜 안에 구축하면 좋겠네요!!
