### ISSUE TITLE
트래픽 초과로 서버 다운 이슈

### ISSUE THREAD

**Issue by realdevelope** [kebin0613/SSAC_Team#39]
## 문제
- 12월 06일 18:00경 트래픽 초과로 저희 '요소수 맵' 서버 가 다운되는 문제가 발생했습니다.
해당 프로젝트가 이렇게 이슈가 되어 사람들이 많이 이용 하실줄 몰랐기에 저희 모두 예상하지 못함.
![hnhnhnhnhnh](https://user-images.githubusercontent.com/48710889/144762840-888960ac-a59e-4476-9cdb-1eb7d17dff9b.PNG)
(해당 이미지는 실제 서버 다운 되었을 때의 이미지가 아님을 알려드립니다
출처 : https://www.asiatoday.co.kr/view.php?key=20200605001127237 )

## 문제분석 및 원인
- 하나의 인스턴스로 서버를 두는 것 자체가 트래픽 감당하기가 힘든데,
  저희는 심지어 프리티어 인스턴스 하나를 서버로 두고 있었기 때문
- 지인분들에게 소개하고 한번에 몰려 들어오시면서 생긴 문제로 추정

## 대처
- 우선 인스턴스 재부팅을 하였고, 벨로그에 긴급공지를 함
- 팀원 모두 온라인으로 집결하여 해결방안 모의

## 해결방안
- 서버비용을 가장 절감하면서, 부하를 분산시키는 나름 최적의 구조를 설정함
->  Elastic Load Balancing 로 프리티어 인스턴스를 2개를 두고, proxy서버, s3(이미지) 의 구조로 재구성
![LB](https://user-images.githubusercontent.com/48710889/144863822-c4609a32-cc59-40fe-8e7c-ee852de3681c.jpg)

## 아쉬운점
- Iac 구축중 프리티어다 보니 서버스펙이 약해 Docker에서 image build가 제대로 되지 않는 현상 발생
-> 따라서 프리티어 말고 한단계 위인 요금제로 변경예정
- 위와같은 구조로 Iac 구성해본적이 없어서 구축 하는데 8시간이 넘게 걸림..

## 예상요금
- 최소 20,000 ~ 최대 100,000 으로 예상 해봅니다.
- 상황에 따라 팀원들과 1/n 혹은 구글 애드샌드를 도입하여 서버비를 충당할 예정입니다.

## 더 효율적인 대처방안이 있으시면 자유롭게 말씀해주세요!!

**Comment by seungwanRyu01** [comment]
클라우드 프론트라는 방법이 있는 데 그것을 사용하지 않고 왜 로드밸런싱을 선택하셨나요??

**Comment by Bigjade97** [comment]
S3 이미지를 넣는 이유 다시 한번 설명해주실 수 있을까요?

**Comment by seungwanRyu01** [comment]
올려주신 이슈보고 잘 이해했습니다! 근데 이거 말고도 클라우드 프론트라는 방법이 있는 데 왜 로드밸런싱을 사용하신 건가요??

**Comment by sue6e2** [comment]
아마 트래픽 초과로 서버가 다운되는 이유 중에 이미지 요청이 초당 50개 이상 날라 오는 것이 있었기 때문인것 같아요. S3에 따로 이미지들을 넣어주어 서버를 거치지 않게 하여 트래픽 초과 문제를 막으려는 것이에요!

**Comment by seungwanRyu01** [comment]
저번 온라인 화상회의에서 로드밸런스 요금제를 쓰지 않고 직접 구축하셨던데 번거로운 과정이었음에도 왜 구축을 하셨을까요?? 이슈 사항이랑 해결 방법 잘 읽었고 저도 모르는 부분을 덕분에 잘 해결했습니다!!

**Comment by realdevelope** [comment]
태규님 지수님 말씀대로입니다ㅎㅎ!!
그리고 승완님 그 이유는 적은 요금으로 최적의 성능을 구현하고자 시작하게 됬고, 
Lac가 구축되어 있는 상태에서 안할 이유가 없었기 때문입니다.

**Comment by seungwanRyu01** [comment]
죄송하지만 추가 질문이 또 있습니다! 클라우드 프론트라는 방법도 있던데 왜 이 방법은 사용 안하신 건지 여쭙고 싶습니다 ...ㅎ

**Comment by Bigjade97** [comment]
클라우드 프론트는 러닝커브가 너무 길어서 사용 안하지 않았을까요? 줌 할때 빠르게 복구하는것을 강조하시던데 ㅎㅎㅎ

**Comment by seungwanRyu01** [comment]
> 클라우드 프론트는 러닝커버가 너무 길어서 사용 안하지 않았을까요? 줌 할때 빠르게 복구하는것을 강조하시던데 ㅎㅎㅎ

대처 신속성 면에서는 클라우드 프론트가 상대적으로 떨어진다는 말씀이시군요...다시 한 번 조사해보겠습니다 감사합니다!

**Comment by realdevelope** [comment]
클라우드 프론트 이런게 있었군요... 태규님 코멘트 보고 알아보니 진짜 러닝커브가...
네넵 다운된 서버  복구가 급선무였기에 빠르게  최소비용으로 최적화를 해보고자 ELB를 선택했습니다ㅎㅎ
다음엔 클라우드 프론트도 고려 해봐야겠네요ㅎㅎ!!
