### ISSUE TITLE
React-Bootstrap 적용시 NewsList 스타일 변화 이슈

### ISSUE THREAD

**Issue by seungwanRyu01** [kebin0613/SSAC_Team#4]
react-bootstrap 모듈 설치시 문제는 안됨. 그리고 뉴스 컴포넌트는 `style-components` 모듈을 설치해서 사용하고 있음.

그러나, `./public/index.html` 파일에 아래와 같은 부트스트랩 cdn을 첨부시,

```
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
  crossorigin="anonymous"
/>
```
![image](https://user-images.githubusercontent.com/57697624/142988734-574fbe2d-fbaa-47d2-8c8f-d56acbdf3739.png)

위와 같이 헤드라인 제목이 크게 튀는 현상이 나타나고, cdn을 제거 시,

![image](https://user-images.githubusercontent.com/57697624/142988956-f3b8b0f8-c461-4daa-960e-62b12ff81a65.png)

헤드라인 제목이 원하는 대로 나옴.

**따라서, NewsPage에서는 React-Bootstrap을 사용안하고 Style-Components를 이용해서 화면을 구성하고자 한다.**

**Comment by realdevelope** [comment]
확인했습니다. 
Style-Components만 이용하셔서 진행해주시면 되겠습니다.

**Comment by sue6e2** [comment]
확인했습니다!

**Comment by Bigjade97** [comment]
아하 확인했습니다!!

**Comment by seungwanRyu01** [comment]
확인 모두 감사합니다:)
