### ISSUE TITLE
injection 이슈

### ISSUE THREAD

**Issue by realdevelope** [kebin0613/SSAC_Team#53]
## 문제
- 틈틈히 서버 모니터링 중 Nginx로그를 확인하게 되었는데 해당 이름을 가진 php파일이 있는지 엄청나게 시도한
로그를 발견했습니다. 보안에 취약한 php로 db를 구축했다면 정말 큰일 날뻔했습니다.
- 그래서 로그에 있는 ip를 추적해 보았더니 중국 난산구 선전시 광동성?! 의 한 4성급 호텔로 나왔습니다.
  (해당 이용자 중에 한분이 봇을 돌렸거나, vpn으로 우회 했을꺼라 추정됩니다)

![ㄷㄷ](https://user-images.githubusercontent.com/48710889/145714040-0ec62813-cd9a-4be4-800e-13db7fa9b46d.png)
![ㄷㄷ2](https://user-images.githubusercontent.com/48710889/145714041-fb85f024-86c5-43b9-8cd7-769d92143c88.png)

## 해결방안
- 서버단에서 화이트리스트 기반으로 검증
- 에러 메세지 노출 금지
- 웹 방화벽 사용

**Comment by seungwanRyu01** [comment]
실제로 저희 프로젝트에 해당 이슈를 겪지 않고 db를 구축했다면 정말 아찔할 뻔했네요..
aws의 waf (웹 방화벽)기능도 나중에 꼭 사용해 봐야겠습니다!

**Comment by realdevelope** [comment]
정말 서비스를 하면서 정말 많은 경험을 하네요 정말 잊지 못할 프로젝트일 것 같습니다. 
사실 저희도 서버단에서 하나하나 잡아줘야하는 기술부채가...😂
