### ISSUE TITLE
News API Response Object 정리

### ISSUE THREAD

**Issue by seungwanRyu01** [kebin0613/SSAC_Team#6]
### status

- 데이터 타입 : string
- 요청이 성공했는지 여부를 알려줌. 옵션: `ok`, `error`. 오류의 경우 코드 및 메시지 속성이 채워짐

### totalResults

- 데이터 타입 : int
- 당신의 리퀘스트에 사용 가능한 총 결과 수

### articles

- 데이터 타입 : array[article]
- 리퀘스트의 결과들

### source

- 데이터 타입 : object
- 기사의 출처 중 기사의 `id`와 `name`을 따온 것

### author

- 데이터 타입 : string
- 기사의 저자

### title

- 데이터 타입 : string
- 기사의 헤드라인 제목

### description
- 데이터 타입 : string
- 기사 내용 프리뷰

### url
- 데이터 타입 : string
- 기사 URL에 다이렉트로 접근

### urlToImage
- 데이터 타입 : string
- 기사 URL 이미지

### publishedAt
- 데이터 타입 : string
- 기사 작성 시간

### content
- 데이터 타입 : string
- 200자 제한으로 작성된 기사 본문

**Comment by realdevelope** [comment]
아래 형식과 같이 잘 가져오는 것 확인했습니다.
저희 notion에도 문서화 해주시면 감사하겠습니다 :)

![KakaoTalk_20211124_051747335](https://user-images.githubusercontent.com/48710889/143097767-2f40381f-bced-44f3-805c-f7a0925b2982.jpg)
.

**Comment by sue6e2** [comment]
확인했습니다!

**Comment by Bigjade97** [comment]
확인했습니다 ㅎㅎ

**Comment by seungwanRyu01** [comment]
확인 모두 감사드립니다:)
