### ISSUE TITLE
요소수 관련 기사 크롤링에 대한 이슈

### ISSUE THREAD

**Issue by Bigjade97** [kebin0613/SSAC_Team#7]
# 이슈
- 크롤링을 구현중에 저희같은 정통적인 구조에 크롤러가 개입이 되면 구조자체가 불안정하다는 이슈를 접했습니다. 그래서 대안을 찾아보니 네이버뉴스 API, newsAPI가 있는데 해당 방법으로 진행하는건 어떨까요?

**Comment by sue6e2** [comment]
서버를 하나로 통합하려고 하시는걸까요?  서버를 따로 두면 크게 문제가 되지 않을 것 같습니다.

**Comment by Bigjade97** [comment]
안그래도 그 부분에 대해서 말씀드리려고 했습니다. 현재는 로컬에서 테스트 후 저의 원격 브랜치에 올려놓은 상태인데 api를 사용하는 것보다 서버를 따로 두는게 나을까요?

**Comment by seungwanRyu01** [comment]
그럼 api를 사용하면 백단이 필요가 없게 되겠네요?

**Comment by Bigjade97** [comment]
넵 아마 이 부분은 상훈님과 저희 팀원 다같이 상의해봐야할 것 같습니다. 
서버를 따로두면 데드락 문제는 발생하지 않으나, 구조자체가 불안정해서,,, 어떻게 생각하시나요?

**Comment by realdevelope** [comment]
네 확인했습니다. 여러분들 말씀대로 서버를 하나로 통합하게 되면 크롤러가 대용량의 데이터를 DB에 넣고 있을 때,  노드에서 select 쿼리 날리면 deadlock이 발생해서 서버전체가 뻗어버리게 되고, 서버를 따로 두어 이와같은 문제는 방지하더라도 구조상 크롤러 개입 자체가 구조상 불안정하기 떄문에 api를 사용하는게 구조상 안정적이라 판단됩니다.

**Comment by Bigjade97** [comment]
네네 공수도 줄이고 다같이 프론트에서 빠르게 배포 하는게 어떨까요?

**Comment by sue6e2** [comment]
네 좋습니다. 하긴 데이터도 제공되고, 뉴스api도 제공된다면 백앤드가 필요없는게 맞네요. 그럼 프론트에서 빠르게 배포 진행하시죠

**Comment by Bigjade97** [comment]
네 알겠습니다!
