### ISSUE TITLE
news api 기사의 카드 가로 정렬이 안되는 문제

### ISSUE THREAD

**Issue by seungwanRyu01** [kebin0613/SSAC_Team#9]
'https://newsapi.org/v2/everything?q=요소수&sortBy=publishedAt&pageSize=3&apiKey=a4a7aca69d614cf0a5944c3ec606db96'

위 링크에서 pazeSize를 3으로 설정해서 기사가 한 페이지에 3개까지 출력되도록 설정했습니다. 이렇게 표현을 하기 위해서, 

![image](https://user-images.githubusercontent.com/57697624/143514879-b1cf5ad6-d82a-43c7-8e8d-6085fb62e3a5.png)

이런 형태의 레이아웃을 짜기 위해서 react-bootstrap의 components의 card 형식을 리액트 프로젝트에 옮겨서 test했지만

![image](https://user-images.githubusercontent.com/57697624/143514998-bd35b731-9db2-4210-b453-5875c611603c.png)

위와 같이 세로로 정렬되는 현상이 자꾸 나타납니다. row를 없애거나, d-flex 설정을 셋팅해도 위와 같은 현상이 자꾸 반복됩니다.

<br>

api에서의 default 셋팅이 세로 정렬이라 저런 현상이 나타나는 것인 지 대표님께 도움을 받고자 합니다...

**Comment by Bigjade97** [comment]
코드 한번 볼 수 있을까요?

**Comment by seungwanRyu01** [comment]
아 해결했습니다. NewsList.js 파일로 넘겼던 컴포넌트 자체를 div 태그랑 row 태그로 감싸주었더니 해결되었습니다. 감사합니다:)
